name: Compilar APK con Buildozer

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Generar buildozer.spec
        run: |
          cat << 'EOF' > buildozer.spec
          [app]
          title = Nando
          package.name = nando
          package.domain = org.fernando
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy,requests,reportlab,python-docx,pillow
          orientation = portrait
          fullscreen = 0

          android.permissions = INTERNET
          android.api = 33
          android.minapi = 24
          android.ndk = 25b
          android.archs = arm64-v8a

          [buildozer]
          log_level = 2
          warn_on_root = 1
          EOF

      - name: Compilar APK con Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: Nando-APK
          path: bin/*.apk
